# fly.toml file generated for tunnelto on 2020-06-30T19:24:55-04:00

app = "tunnelto"

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 99999
    soft_limit = 99998

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "10001"

  [[services.http_checks]]
    interval = 10000
    method = "get"
    path = "/health_check"
    protocol = "http"
    timeout = 20000

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 99999
    soft_limit = 99998

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.http_checks]]
    interval = 10000
    method = "get"
    path = "/0xDEADBEEF_HEALTH_CHECK"
    protocol = "http"
    timeout = 20000